export const STUDIO_API_OPENAPI = {
  openapi: "3.1.0",
  info: {
    title: "Yatishara Studio API",
    version: "1.4.1",
    description:
      "REST API for folders, assets, documents, elements, audio, assistance, video edits, AI generation, and direct messaging. Authenticate with Bearer ysk_live_… keys. Messaging routes require the messages scope and are not limited to the API key sandbox folder.",
  },
  servers: [{ url: "/api/v1" }],
  security: [{ bearerAuth: [] }],
  components: {
    securitySchemes: {
      bearerAuth: {
        type: "http",
        scheme: "bearer",
        description: "Studio API key (ysk_live_…)",
      },
    },
  },
  paths: {
    "/": {
      get: { summary: "API root and capability list" },
    },
    "/openapi.json": { get: { summary: "OpenAPI 3.1 document" } },
    "/account": { get: { summary: "Credit balance and subscription" } },
    "/trash": { get: { summary: "List trashed items (?kind=folder|asset|document|element)" } },
    "/folders": {
      get: { summary: "List folders" },
      post: { summary: "Create folder" },
    },
    "/folders/{id}": {
      get: { summary: "Get folder" },
      patch: { summary: "Rename or move folder" },
      delete: { summary: "Move folder to trash" },
    },
    "/folders/{id}/restore": { post: { summary: "Restore folder from trash" } },
    "/folders/{id}/contents": { get: { summary: "Folder contents" } },
    "/assets/{id}": {
      get: { summary: "Get asset with signed URL" },
      patch: { summary: "Rename or move asset" },
      delete: { summary: "Move asset to trash" },
    },
    "/assets/{id}/restore": { post: { summary: "Restore asset from trash" } },
    "/assets/upload": { post: { summary: "Reserve or complete upload URL (two-step)" } },
    "/assets/upload-inline": { post: { summary: "Upload base64 file in one step" } },
    "/documents": {
      post: { summary: "Create document" },
    },
    "/documents/{id}": {
      get: { summary: "Get document" },
      patch: { summary: "Update document" },
      delete: { summary: "Move document to trash" },
    },
    "/documents/{id}/restore": { post: { summary: "Restore document from trash" } },
    "/elements": {
      get: { summary: "List elements" },
      post: { summary: "Create element" },
    },
    "/elements/production-guide": {
      get: { summary: "Build states and generation rules for elements" },
    },
    "/elements/sheet-guide": {
      get: { summary: "Agent guide: ref counts, fidelity rules, sheet workflow" },
    },
    "/elements/{id}": {
      get: { summary: "Get element" },
      patch: { summary: "Rename, move, or update element" },
      delete: { summary: "Move element to trash" },
    },
    "/elements/{id}/restore": { post: { summary: "Restore element from trash" } },
    "/elements/{id}/generate-text-sheet": {
      post: { summary: "Generate element markdown description from refs" },
    },
    "/elements/{id}/generate-sheet": {
      post: { summary: "Generate element reference sheet image" },
    },
    "/style-sheets": { get: { summary: "List Style Sheet elements" } },
    "/style-presets": { get: { summary: "List style presets (Direct/unstyled)" } },
    "/video-models": { get: { summary: "List video models (?scope=mcp for MCP catalog)" } },
    "/catalog/script-types": { get: { summary: "List scriptType values" } },
    "/catalog/reference-intents": { get: { summary: "List referenceIntent values" } },
    "/voices": { get: { summary: "Explore ElevenLabs voices" } },
    "/voices/saved": {
      get: { summary: "List saved voices" },
      post: { summary: "Save a voice favorite" },
    },
    "/voices/saved/{voiceId}": { delete: { summary: "Remove a saved voice" } },
    "/generations": {
      get: { summary: "List generation jobs" },
      post: { summary: "Generate image, video, script, or audio" },
    },
    "/generations/estimate": { post: { summary: "Estimate credit cost" } },
    "/generations/estimate-batch": { post: { summary: "Estimate multi-item production budget" } },
    "/generations/{id}": { get: { summary: "Get generation job" } },
    "/assistance/briefs": { post: { summary: "Ensure assisted brief (+ thread)" } },
    "/assistance/briefs/{briefId}": {
      get: { summary: "Get assisted brief" },
      patch: { summary: "Edit assisted brief payload" },
    },
    "/assistance/briefs/{briefId}/production": {
      patch: { summary: "Patch brief production knobs" },
    },
    "/assistance/briefs/{briefId}/approve": {
      post: { summary: "Approve brief and start generation" },
    },
    "/assistance/briefs/{briefId}/reject": {
      post: { summary: "Reject / abandon brief" },
    },
    "/assistance/threads/{threadId}/brief": {
      get: { summary: "Get brief for thread" },
    },
    "/assistance/approvals": {
      get: { summary: "List pending approvals (?status=pending)" },
    },
    "/assistance/approvals/{id}/decide": {
      post: { summary: "Approve or deny workspace side-effect approval" },
    },
    "/edits": {
      get: { summary: "List video edits (?folderId=)" },
      post: { summary: "Create video edit project" },
    },
    "/edits/{id}": {
      get: { summary: "Get video edit project" },
      put: { summary: "Save full project JSON" },
      patch: { summary: "Rename or move edit" },
    },
    "/edits/{id}/export": {
      post: {
        summary: "Export edit to a video or audio asset",
        description:
          "Optional body: name, exportKind (video|audio), exportResolution (720p|1080p|4K; video default 1080p), audioFormat (mp3|wav|m4a; audio default mp3).",
      },
    },
    "/edits/{id}/package": {
      get: { summary: "Portable .studio package manifest" },
      post: { summary: "Portable .studio package manifest (optional expiresUnix)" },
    },
    "/edits/{id}/clips/download": {
      post: {
        summary: "Download trimmed clip segment",
        description: "Body: clipId preferred, or assetId+trimIn+trimOut; mode video|audio.",
      },
    },
    "/edits/{id}/text": { post: { summary: "Add text/title overlay clip" } },
    "/edits/{id}/clips/duplicate": { post: { summary: "Duplicate a clip" } },
    "/edits/{id}/clips/detach-audio": { post: { summary: "Detach audio bed from video clip" } },
    "/edits/{id}/tracks/{trackId}": { patch: { summary: "Mute/unmute track" } },
    "/edits/{id}/frame-ratio": { post: { summary: "Set canvas frame ratio" } },
    "/messages/conversations": {
      get: { summary: "List DM conversations (?labelId=)" },
      post: { summary: "Open or create DM by username" },
    },
    "/messages/search": { get: { summary: "Search people, chats, messages, labels (?q=)" } },
    "/messages/unread-count": { get: { summary: "Unread conversation count" } },
    "/messages/conversations/{id}/messages": {
      get: { summary: "List messages (?limit=)" },
      post: { summary: "Send text message" },
    },
    "/messages/conversations/{id}/images": { post: { summary: "Send image message (assetId)" } },
    "/messages/conversations/{id}/voice": { post: { summary: "Send voice note (assetId + durationSec)" } },
    "/messages/conversations/{id}/media": {
      post: {
        summary:
          "Send Studio media (UI Choose/Share). Default delivery=file → peer Messages + image/video bubbles",
      },
    },
    "/messages/conversations/{id}/share": { post: { summary: "Share feed post/comment into DM" } },
    "/messages/conversations/{id}/read": { post: { summary: "Mark conversation read" } },
    "/messages/labels": {
      get: { summary: "List DM labels" },
      post: { summary: "Create DM label" },
    },
    "/messages/labels/{id}": {
      patch: { summary: "Update DM label" },
      delete: { summary: "Delete DM label" },
    },
    "/messages/peers/{userId}/labels": {
      get: { summary: "Labels assigned to peer" },
      put: { summary: "Replace peer label memberships" },
    },
    "/messages/peers/{userId}/panel": { get: { summary: "Peer sidebar panel" } },
    "/messages/peers/{userId}/notes": {
      get: { summary: "List private notes about peer" },
      post: { summary: "Add private note about peer" },
    },
    "/messages/notes/{id}": {
      patch: { summary: "Update private note" },
      delete: { summary: "Delete private note" },
    },
    "/messages/peers/{userId}/block": { post: { summary: "Block peer" } },
    "/messages/peers/{userId}/unblock": { post: { summary: "Unblock peer" } },
    "/profiles/me": {
      get: { summary: "Get API key owner public profile" },
      patch: { summary: "Update owner profile (bio, avatar, visibility, contacts)" },
    },
    "/profiles/username-available": { get: { summary: "Check username availability (?username=)" } },
    "/profiles/claim-username": { post: { summary: "Claim or set owner username" } },
    "/profiles/change-username": { post: { summary: "Rename owner username" } },
    "/profiles/{username}": { get: { summary: "Get public profile by username" } },
    "/profiles/{profileId}/follow": {
      post: { summary: "Follow profile" },
      delete: { summary: "Unfollow profile" },
    },
    "/profiles/me/following": { get: { summary: "List profiles the owner follows" } },
    "/profiles/people": { get: { summary: "List public profiles not followed" } },
    "/feed": { get: { summary: "Ranked feed (?mode=forYou|following&limit=&seedPostId=)" } },
    "/feed/posts": {
      get: { summary: "Public posts for username (?username=&limit=)" },
      post: { summary: "Share asset to public feed" },
    },
    "/feed/collection": { get: { summary: "Owner collection (?kind=saved|liked|shared)" } },
    "/feed/posts/by-asset/{assetId}": { delete: { summary: "Unshare asset from public profile" } },
    "/feed/posts/{postId}": { patch: { summary: "Update post caption" } },
    "/feed/assets/{assetId}/shared": { get: { summary: "Whether asset is shared by owner" } },
    "/feed/shared-asset-ids": { get: { summary: "Owner shared asset IDs" } },
    "/feed/posts/{postId}/media": { get: { summary: "Signed post media URLs" } },
    "/feed/posts/{postId}/like": { post: { summary: "Toggle like" } },
    "/feed/posts/{postId}/save": { post: { summary: "Toggle save" } },
    "/feed/posts/{postId}/share": { post: { summary: "Record share engagement" } },
    "/feed/posts/{postId}/view": { post: { summary: "Record post view" } },
    "/feed/posts/{postId}/comments": {
      get: { summary: "List top-level comments" },
      post: { summary: "Add comment or reply" },
    },
    "/feed/comments/{parentId}/replies": { get: { summary: "List comment replies" } },
    "/feed/comments/{commentId}/like": { post: { summary: "Toggle comment like" } },
    "/feed/comments/{commentId}": { delete: { summary: "Delete comment" } },
    "/feed/suggest/hashtags": { get: { summary: "Hashtag autocomplete (?query=&limit=)" } },
    "/feed/suggest/people": { get: { summary: "People autocomplete (?query=&limit=)" } },
    "/account/payments": { get: { summary: "List recent payments (top-ups)" } },
    "/account/payments/{id}": { get: { summary: "Get payment by id" } },
    "/account/credits": { get: { summary: "Paginated credit ledger (?numItems=&cursor=)" } },
    "/account/plans": { get: { summary: "List subscription plans" } },
    "/account/pricing": { get: { summary: "Credit unit price + sample generation costs" } },
    "/account/storage": { get: { summary: "Storage usage and projected charge" } },
    "/account/subscription": { get: { summary: "Balance + active subscription summary" } },
    "/notifications": { get: { summary: "List in-app notifications" } },
    "/notifications/{id}/read": { post: { summary: "Mark notification read" } },
    "/network/offers": { get: { summary: "List published Creative Network offers" } },
    "/network/offers/{slug}": { get: { summary: "Get published offer by slug" } },
    "/network/offers/{offerId}/reviews": { get: { summary: "Public offer reviews" } },
    "/network/offers/{offerId}/quote": { get: { summary: "Quote book price in credits" } },
    "/network/offers/{offerId}/book": { post: { summary: "Book offer (escrow hold)" } },
    "/network/sellers/{username}/offers": { get: { summary: "Published offers by seller username" } },
    "/network/sellers/{username}/hire": { get: { summary: "Whether viewer can hire seller" } },
    "/network/sellers/approved/{userId}": { get: { summary: "Whether userId is approved seller" } },
    "/network/me/seller": { get: { summary: "Owner seller status" } },
    "/network/me/offers": {
      get: { summary: "List owner offers (seller)" },
      post: { summary: "Create offer draft" },
    },
    "/network/me/offers/{offerId}": { patch: { summary: "Update offer" } },
    "/network/me/offers/{offerId}/status": { post: { summary: "Set offer status" } },
    "/network/jobs/seller": { get: { summary: "Jobs as seller" } },
    "/network/jobs/buyer": { get: { summary: "Jobs as buyer" } },
    "/network/jobs/with/{peerUserId}": { get: { summary: "Jobs with peer" } },
    "/network/jobs/{jobId}": { get: { summary: "Job detail" } },
    "/network/jobs/{jobId}/deliver": { post: { summary: "Seller deliver assets" } },
    "/network/jobs/{jobId}/accept": { post: { summary: "Buyer accept delivery" } },
    "/network/jobs/{jobId}/cancel": { post: { summary: "Cancel before delivery" } },
    "/network/jobs/{jobId}/review": { post: { summary: "Submit job review" } },
    "/network/listings": {
      get: { summary: "Browse stock-audio listings" },
      post: { summary: "List owned audio (prepare→copy→commit)" },
    },
    "/network/listings/quote": { get: { summary: "Quote list price (?assetId=)" } },
    "/network/listings/{listingId}": { get: { summary: "Get listing card" } },
    "/network/listings/{listingId}/prepare-purchase": { post: { summary: "Prepare purchase" } },
    "/network/listings/{listingId}/purchase": { post: { summary: "Purchase listing (prepare→copy→finalize)" } },
    "/network/me/listings": { get: { summary: "Seller listings" } },
    "/network/me/listings/summary": { get: { summary: "Seller store summary" } },
    "/network/me/listings/for-asset/{assetId}": { get: { summary: "Seller listing for asset" } },
    "/network/me/listings/{listingId}": { get: { summary: "Seller listing detail" } },
    "/network/me/listings/prepare": { post: { summary: "Prepare list on network" } },
    "/network/me/listings/commit": { post: { summary: "Commit list on network" } },
    "/network/me/listings/{listingId}/unlist": { post: { summary: "Unlist from network" } },
    "/network/purchases/{purchaseId}/finalize": { post: { summary: "Finalize purchase copy" } },
  },
} as const;

export const STUDIO_API_ROOT = {
  name: "Yatishara Studio API",
  version: "1.4.1",
  documentation: "/api/v1/openapi.json",
  scopes: ["read", "write", "generate", "messages", "social", "marketplace"],
  endpoints: [
    "GET /account",
    "GET /account/payments",
    "GET /account/payments/:id",
    "GET /account/credits",
    "GET /account/plans",
    "GET /account/pricing",
    "GET /account/storage",
    "GET /account/subscription",
    "GET /notifications",
    "POST /notifications/:id/read",
    "GET /trash",
    "GET|POST /folders",
    "GET|PATCH|DELETE /folders/:id",
    "POST /folders/:id/restore",
    "GET /folders/:id/contents",
    "GET|PATCH|DELETE /assets/:id",
    "POST /assets/:id/restore",
    "POST /assets/upload",
    "POST /assets/upload-inline",
    "POST /documents",
    "GET|PATCH|DELETE /documents/:id",
    "POST /documents/:id/restore",
    "GET|POST /elements",
    "GET /elements/production-guide",
    "GET /elements/sheet-guide",
    "GET|PATCH|DELETE /elements/:id",
    "POST /elements/:id/restore",
    "POST /elements/:id/generate-text-sheet",
    "POST /elements/:id/generate-sheet",
    "GET /style-sheets",
    "GET /style-presets",
    "GET /video-models",
    "GET /catalog/script-types",
    "GET /catalog/reference-intents",
    "GET /voices",
    "GET|POST /voices/saved",
    "DELETE /voices/saved/:voiceId",
    "GET|POST /generations",
    "POST /generations/estimate",
    "POST /generations/estimate-batch",
    "GET /generations/:id",
    "POST /assistance/briefs",
    "GET /assistance/briefs/:briefId",
    "PATCH /assistance/briefs/:briefId",
    "PATCH /assistance/briefs/:briefId/production",
    "POST /assistance/briefs/:briefId/approve",
    "POST /assistance/briefs/:briefId/reject",
    "GET /assistance/threads/:threadId/brief",
    "GET /assistance/approvals",
    "POST /assistance/approvals/:id/decide",
    "GET|POST /edits",
    "GET|PUT|PATCH /edits/:id",
    "POST /edits/:id/export",
    "GET|POST /edits/:id/package",
    "POST /edits/:id/clips/download",
    "GET|POST /messages/conversations",
    "GET /messages/search",
    "GET /messages/unread-count",
    "GET|POST /messages/conversations/:id/messages",
    "POST /messages/conversations/:id/images",
    "POST /messages/conversations/:id/voice",
    "POST /messages/conversations/:id/media",
    "POST /messages/conversations/:id/share",
    "POST /messages/conversations/:id/read",
    "GET|POST /messages/labels",
    "PATCH|DELETE /messages/labels/:id",
    "GET|PUT /messages/peers/:userId/labels",
    "GET /messages/peers/:userId/panel",
    "GET|POST /messages/peers/:userId/notes",
    "PATCH|DELETE /messages/notes/:id",
    "POST /messages/peers/:userId/block",
    "POST /messages/peers/:userId/unblock",
    "GET|PATCH /profiles/me",
    "GET /profiles/username-available",
    "POST /profiles/claim-username",
    "POST /profiles/change-username",
    "GET /profiles/:username",
    "POST|DELETE /profiles/:profileId/follow",
    "GET /profiles/me/following",
    "GET /profiles/people",
    "GET /feed",
    "GET|POST /feed/posts",
    "GET /feed/collection",
    "DELETE /feed/posts/by-asset/:assetId",
    "PATCH /feed/posts/:postId",
    "GET /feed/assets/:assetId/shared",
    "GET /feed/shared-asset-ids",
    "GET /feed/posts/:postId/media",
    "POST /feed/posts/:postId/like",
    "POST /feed/posts/:postId/save",
    "POST /feed/posts/:postId/share",
    "POST /feed/posts/:postId/view",
    "GET|POST /feed/posts/:postId/comments",
    "GET /feed/comments/:parentId/replies",
    "POST /feed/comments/:commentId/like",
    "DELETE /feed/comments/:commentId",
    "GET /feed/suggest/hashtags",
    "GET /feed/suggest/people",
    "GET /network/offers",
    "GET /network/offers/:slug",
    "GET /network/offers/:offerId/reviews",
    "GET /network/offers/:offerId/quote",
    "POST /network/offers/:offerId/book",
    "GET /network/sellers/:username/offers",
    "GET /network/sellers/:username/hire",
    "GET /network/sellers/approved/:userId",
    "GET /network/me/seller",
    "GET|POST /network/me/offers",
    "PATCH /network/me/offers/:offerId",
    "POST /network/me/offers/:offerId/status",
    "GET /network/jobs/seller",
    "GET /network/jobs/buyer",
    "GET /network/jobs/with/:peerUserId",
    "GET /network/jobs/:jobId",
    "POST /network/jobs/:jobId/deliver",
    "POST /network/jobs/:jobId/accept",
    "POST /network/jobs/:jobId/cancel",
    "POST /network/jobs/:jobId/review",
    "GET|POST /network/listings",
    "GET /network/listings/quote",
    "GET /network/listings/:listingId",
    "POST /network/listings/:listingId/prepare-purchase",
    "POST /network/listings/:listingId/purchase",
    "GET /network/me/listings",
    "GET /network/me/listings/summary",
    "GET /network/me/listings/for-asset/:assetId",
    "GET /network/me/listings/:listingId",
    "POST /network/me/listings/prepare",
    "POST /network/me/listings/commit",
    "POST /network/me/listings/:listingId/unlist",
    "POST /network/purchases/:purchaseId/finalize",
  ],
};
