import type { LucideIcon } from "lucide-react";
import {
  AlarmClock,
  Archive,
  AtSign,
  Award,
  Baby,
  Bell,
  Bike,
  Bookmark,
  Briefcase,
  Brush,
  Building2,
  Cake,
  Calendar,
  Camera,
  Car,
  Cat,
  CheckCircle2,
  Clapperboard,
  ClipboardList,
  Clock,
  Cloud,
  Coffee,
  Coins,
  CreditCard,
  Crown,
  Dog,
  DollarSign,
  Dumbbell,
  FileText,
  Film,
  Fish,
  Flag,
  Flame,
  Flower2,
  Folder,
  Gamepad2,
  Gem,
  Gift,
  Globe,
  GraduationCap,
  Hammer,
  Handshake,
  Hash,
  Headphones,
  Heart,
  HelpCircle,
  Home,
  Image,
  Inbox,
  Info,
  Key,
  Landmark,
  Layers,
  Leaf,
  Lightbulb,
  Lock,
  Mail,
  MapPin,
  Megaphone,
  MessageCircle,
  Mic,
  Moon,
  Mountain,
  Music,
  Palette,
  Phone,
  PiggyBank,
  Pin,
  Pizza,
  Plane,
  PlusCircle,
  Radio,
  Receipt,
  Rocket,
  Scissors,
  Settings,
  Share2,
  Shield,
  Ship,
  Shirt,
  ShoppingBag,
  Smile,
  Sparkles,
  Star,
  Stethoscope,
  Sun,
  Tag,
  Target,
  Tent,
  ThumbsUp,
  TreePine,
  Trophy,
  Tv,
  Umbrella,
  UserRound,
  Users,
  Video,
  Wallet,
  Wine,
  Wrench,
  Zap,
} from "lucide-react";

/** Keep in sync with convex/dmLabels.ts DM_LABEL_ICONS. */
export const DM_LABEL_ICON_OPTIONS: Array<{
  key: string;
  Icon: LucideIcon;
  label: string;
}> = [
  { key: "tag", Icon: Tag, label: "Tag" },
  { key: "briefcase", Icon: Briefcase, label: "Work" },
  { key: "heart", Icon: Heart, label: "Favorites" },
  { key: "star", Icon: Star, label: "Star" },
  { key: "home", Icon: Home, label: "Home" },
  { key: "users", Icon: Users, label: "People" },
  { key: "user-round", Icon: UserRound, label: "Person" },
  { key: "handshake", Icon: Handshake, label: "Clients" },
  { key: "shopping-bag", Icon: ShoppingBag, label: "Shopping" },
  { key: "graduation-cap", Icon: GraduationCap, label: "School" },
  { key: "plane", Icon: Plane, label: "Travel" },
  { key: "car", Icon: Car, label: "Car" },
  { key: "bike", Icon: Bike, label: "Bike" },
  { key: "ship", Icon: Ship, label: "Boat" },
  { key: "music", Icon: Music, label: "Music" },
  { key: "headphones", Icon: Headphones, label: "Audio" },
  { key: "mic", Icon: Mic, label: "Mic" },
  { key: "camera", Icon: Camera, label: "Camera" },
  { key: "image", Icon: Image, label: "Photo" },
  { key: "video", Icon: Video, label: "Video" },
  { key: "film", Icon: Film, label: "Film" },
  { key: "clapperboard", Icon: Clapperboard, label: "Shoot" },
  { key: "tv", Icon: Tv, label: "TV" },
  { key: "radio", Icon: Radio, label: "Radio" },
  { key: "coffee", Icon: Coffee, label: "Coffee" },
  { key: "pizza", Icon: Pizza, label: "Food" },
  { key: "wine", Icon: Wine, label: "Drinks" },
  { key: "cake", Icon: Cake, label: "Party" },
  { key: "gift", Icon: Gift, label: "Gift" },
  { key: "gamepad-2", Icon: Gamepad2, label: "Games" },
  { key: "dumbbell", Icon: Dumbbell, label: "Fitness" },
  { key: "landmark", Icon: Landmark, label: "Finance" },
  { key: "wallet", Icon: Wallet, label: "Wallet" },
  { key: "credit-card", Icon: CreditCard, label: "Card" },
  { key: "coins", Icon: Coins, label: "Coins" },
  { key: "dollar-sign", Icon: DollarSign, label: "Money" },
  { key: "piggy-bank", Icon: PiggyBank, label: "Savings" },
  { key: "receipt", Icon: Receipt, label: "Invoice" },
  { key: "stethoscope", Icon: Stethoscope, label: "Health" },
  { key: "wrench", Icon: Wrench, label: "Tools" },
  { key: "hammer", Icon: Hammer, label: "Build" },
  { key: "scissors", Icon: Scissors, label: "Cut" },
  { key: "settings", Icon: Settings, label: "Settings" },
  { key: "sparkles", Icon: Sparkles, label: "Sparkles" },
  { key: "bookmark", Icon: Bookmark, label: "Bookmark" },
  { key: "flag", Icon: Flag, label: "Flag" },
  { key: "pin", Icon: Pin, label: "Pin" },
  { key: "map-pin", Icon: MapPin, label: "Place" },
  { key: "building-2", Icon: Building2, label: "Business" },
  { key: "baby", Icon: Baby, label: "Family" },
  { key: "dog", Icon: Dog, label: "Pets" },
  { key: "cat", Icon: Cat, label: "Cat" },
  { key: "fish", Icon: Fish, label: "Fish" },
  { key: "palette", Icon: Palette, label: "Creative" },
  { key: "brush", Icon: Brush, label: "Art" },
  { key: "layers", Icon: Layers, label: "Layers" },
  { key: "megaphone", Icon: Megaphone, label: "Promo" },
  { key: "phone", Icon: Phone, label: "Call" },
  { key: "mail", Icon: Mail, label: "Mail" },
  { key: "message-circle", Icon: MessageCircle, label: "Chat" },
  { key: "at-sign", Icon: AtSign, label: "Mention" },
  { key: "globe", Icon: Globe, label: "Web" },
  { key: "share-2", Icon: Share2, label: "Share" },
  { key: "thumbs-up", Icon: ThumbsUp, label: "Like" },
  { key: "smile", Icon: Smile, label: "Fun" },
  { key: "bell", Icon: Bell, label: "Alerts" },
  { key: "clock", Icon: Clock, label: "Later" },
  { key: "alarm-clock", Icon: AlarmClock, label: "Urgent" },
  { key: "calendar", Icon: Calendar, label: "Calendar" },
  { key: "check-circle-2", Icon: CheckCircle2, label: "Done" },
  { key: "plus-circle", Icon: PlusCircle, label: "New" },
  { key: "target", Icon: Target, label: "Goal" },
  { key: "zap", Icon: Zap, label: "Energy" },
  { key: "flame", Icon: Flame, label: "Hot" },
  { key: "trophy", Icon: Trophy, label: "Win" },
  { key: "award", Icon: Award, label: "Award" },
  { key: "rocket", Icon: Rocket, label: "Launch" },
  { key: "lightbulb", Icon: Lightbulb, label: "Idea" },
  { key: "file-text", Icon: FileText, label: "Docs" },
  { key: "folder", Icon: Folder, label: "Folder" },
  { key: "inbox", Icon: Inbox, label: "Inbox" },
  { key: "archive", Icon: Archive, label: "Archive" },
  { key: "clipboard-list", Icon: ClipboardList, label: "List" },
  { key: "shield", Icon: Shield, label: "Safe" },
  { key: "lock", Icon: Lock, label: "Private" },
  { key: "key", Icon: Key, label: "Access" },
  { key: "info", Icon: Info, label: "Info" },
  { key: "help-circle", Icon: HelpCircle, label: "Help" },
  { key: "hash", Icon: Hash, label: "Topic" },
  { key: "sun", Icon: Sun, label: "Day" },
  { key: "moon", Icon: Moon, label: "Night" },
  { key: "cloud", Icon: Cloud, label: "Cloud" },
  { key: "umbrella", Icon: Umbrella, label: "Weather" },
  { key: "tree-pine", Icon: TreePine, label: "Nature" },
  { key: "mountain", Icon: Mountain, label: "Outdoors" },
  { key: "flower-2", Icon: Flower2, label: "Flower" },
  { key: "leaf", Icon: Leaf, label: "Green" },
  { key: "tent", Icon: Tent, label: "Camp" },
  { key: "shirt", Icon: Shirt, label: "Fashion" },
  { key: "gem", Icon: Gem, label: "Gem" },
  { key: "crown", Icon: Crown, label: "VIP" },
];

const byKey = new Map(DM_LABEL_ICON_OPTIONS.map((row) => [row.key, row.Icon]));

export function dmLabelIcon(key: string): LucideIcon {
  return byKey.get(key) ?? Tag;
}
